# Generated by Django 5.1.2 on 2024-11-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_datapoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
